
server:
 port: 8765

spring:
  application:
    name: zuul-cloud-gateway
  

  cloud:
   gateway:
      routes:
      - id: user-service
        uri: http://localhost:9002/users/
        predicates:
        - Path=/users/**
        
      - id: department-service
        uri: http://localhost:9001/departments/ 
        predicates:
         - Path=/departments/**

eureka:
  client:
    service-url:
     defaultZone: http://localHost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
      